### PR TITLE
Add support for once only controller

### PR DESCRIPTION
**Pull request by kirillyu**

### CODE REVIEW

**Comment by kirillyu** [comment]
One more cool improvment. I really need this for cases like authorization or for getting props/setting vars in the begging of thread group.

**Comment by rabelenda** [comment]
Great contribution again! thanks!

I have added some details to fix. We can fix them after merge if you like to speed things up.

Additionally, would be nice to add in user guide some section about once only controller for beginners, an example as the one you mention in the PR comment (the auth) would be a great example for new users.

Regards.

**Comment by kirillyu** [comment]
Ok , I will add it :)

**Comment by kirillyu** [comment]
Fixed

**Comment by rabelenda** [comment]
Awesome, thank you very much!

**Comment by kirillyu** [comment]
Hm, why are there checkstyle error? I have checked it before pushing

**Pull request merged**
