### PR TITLE
Overloading DslVariables constructor to allow element name to be specified

### PR DESCRIPTION
**Pull request by andy-tarr**
…ified

### CODE REVIEW

**Comment by rabelenda** [comment]
Hello, thank you for contributing this pull request.

What is the main reason behind adding a name to the element? Can you provide examples? In general we have decided to provide methods to specify names only to scenarios that the name has some functional effect on the test plan (eg: name of a generated variable or log), to keep the number of methods in the API short.

**Comment by andy-tarr** [comment]
Hi, the main reason is that our tests have different sets of variables such as environment variables and post body request variables which we want to keep separate. 
Having 2 UDVs called the same thing in the test plan isn't great for an engineer trying to debug an issue

**Comment by andy-tarr** [comment]
yes, we are using saveToJmx

**Comment by andy-tarr** [comment]
@rabelenda could this be merged please?

**Pull request merged**
